{
	"version": 1517843782,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/cardelement-sheet0.png",
		"images/cardelement-sheet1.png",
		"images/cardelement-sheet2.png",
		"images/cardelementshadow-sheet0.png",
		"images/cardelementshadow-sheet1.png",
		"images/cardelementshadow-sheet2.png",
		"images/btnbacktomain-sheet0.png",
		"images/btnbacktomain-sheet1.png",
		"images/btnsoundunmute-sheet0.png",
		"images/btnsoundunmute-sheet1.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundmute-sheet1.png",
		"images/btnplay-sheet0.png",
		"images/btnplay-sheet1.png",
		"images/btnleft-sheet0.png",
		"images/btnleft-sheet1.png",
		"images/btnleft-sheet2.png",
		"images/btnpause-sheet0.png",
		"images/btnpause-sheet1.png",
		"images/btnrestart-sheet0.png",
		"images/btnrestart-sheet1.png",
		"images/btnright-sheet0.png",
		"images/btnright-sheet1.png",
		"images/btnright-sheet2.png",
		"images/btnskip-sheet0.png",
		"images/btnskip-sheet1.png",
		"images/btnmoregames-sheet0.png",
		"images/btnmoregames-sheet1.png",
		"images/logoblackmoon-sheet0.png",
		"images/pausecurtain.png",
		"images/covergamemode-sheet0.png",
		"images/covergamemode-sheet1.png",
		"images/bmlogo-sheet0.png",
		"images/bgpart-sheet0.png",
		"images/bgpart-sheet1.png",
		"images/bmlogo2-sheet0.png",
		"images/coverbackground-sheet0.png",
		"images/gameplaybackground1-sheet0.png",
		"images/highscoreimg-sheet0.png",
		"images/licznikczasu_-sheet0.png",
		"images/logo-sheet0.png",
		"images/pausedcurtain-sheet0.png",
		"images/popupcurtain-sheet0.png",
		"images/pause_label-sheet0.png",
		"images/preloadergraphics_png2-sheet0.png",
		"images/score-sheet0.png",
		"images/scorepanel-sheet0.png",
		"images/scoresegment-sheet0.png",
		"images/tryagain-sheet0.png",
		"images/youlost-sheet0.png",
		"images/youwon-sheet0.png",
		"images/preloaderfont.png",
		"images/scoretxt.png",
		"images/timesf.png",
		"images/preloaderfont2.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/flashscreen-sheet0.png",
		"images/countdown-sheet0.png",
		"images/countdown-sheet1.png",
		"images/countdown-sheet2.png",
		"images/won-sheet0.png",
		"images/htp_taponthesametwinz-sheet0.png",
		"images/wykrzyknikkolopunktowkiedyjetracisz-sheet0.png",
		"images/infofontbig.png",
		"images/hitlay-sheet0.png",
		"images/loadingicon-sheet0.png",
		"images/mark1-sheet0.png",
		"images/frameborder-sheet0.png",
		"images/turnrules-sheet0.png",
		"images/turnrules-sheet1.png",
		"images/turnrules-sheet2.png",
		"images/tapicon_-sheet0.png",
		"images/howtoplaylabel-sheet0.png",
		"images/letterkey_-sheet0.png",
		"images/letterkey_-sheet1.png",
		"images/letterkey_-sheet2.png",
		"images/letterline-sheet0.png",
		"images/animacjanadbelkaktorazmieniawartosc_-sheet0.png",
		"images/animacjanadbelkaktorazmieniawartosc_-sheet1.png",
		"images/paneldotrybu-sheet0.png",
		"images/sprite-sheet0.png",
		"images/cardsplash-sheet0.png",
		"images/cardsplash-sheet1.png",
		"images/outrostar-sheet0.png",
		"images/turnsfont.png",
		"images/preloadergraphics_png3-sheet0.png",
		"media/bling_01.m4a",
		"media/bling_01.ogg",
		"media/bling_02.m4a",
		"media/bling_02.ogg",
		"media/checkpoint_01.m4a",
		"media/checkpoint_01.ogg",
		"media/checkpoint_02b.m4a",
		"media/checkpoint_02b.ogg",
		"media/click on the proper item_1.m4a",
		"media/click on the proper item_1.ogg",
		"media/click on the proper item_2.m4a",
		"media/click on the proper item_2.ogg",
		"media/click on the proper item_3.m4a",
		"media/click on the proper item_3.ogg",
		"media/click on the proper item_4.m4a",
		"media/click on the proper item_4.ogg",
		"media/click on the proper item_7.m4a",
		"media/click on the proper item_7.ogg",
		"media/first jump_2.m4a",
		"media/first jump_2.ogg",
		"media/moving_blocks_1.m4a",
		"media/moving_blocks_1.ogg",
		"media/moving_blocks_2.m4a",
		"media/moving_blocks_2.ogg",
		"media/moving_blocks_3.m4a",
		"media/moving_blocks_3.ogg",
		"media/moving_blocks_4.m4a",
		"media/moving_blocks_4.ogg",
		"media/moving_blocks_5.m4a",
		"media/moving_blocks_5.ogg",
		"media/moving_blocks_6.m4a",
		"media/moving_blocks_6.ogg",
		"media/moving_blocks_7.m4a",
		"media/moving_blocks_7.ogg",
		"media/moving_blocks_8.m4a",
		"media/moving_blocks_8.ogg",
		"media/pickup medal_01.m4a",
		"media/pickup medal_01.ogg",
		"media/pop die3.m4a",
		"media/pop die3.ogg",
		"media/releasing the wall_1.m4a",
		"media/releasing the wall_1.ogg",
		"media/vegetable _tap_click__1.m4a",
		"media/vegetable _tap_click__1.ogg",
		"media/vegetable _tap_click__2.m4a",
		"media/vegetable _tap_click__2.ogg",
		"media/vegetable _tap_click__3.m4a",
		"media/vegetable _tap_click__3.ogg",
		"media/vegetable _tap_click__4.m4a",
		"media/vegetable _tap_click__4.ogg",
		"media/vegetable _tap_click__5.m4a",
		"media/vegetable _tap_click__5.ogg",
		"media/vegetable _tap_click__6.m4a",
		"media/vegetable _tap_click__6.ogg",
		"media/vegetable _tap_click__7.m4a",
		"media/vegetable _tap_click__7.ogg",
		"media/scoring 01b.m4a",
		"media/scoring 01b.ogg",
		"media/wall jump_3b.m4a",
		"media/wall jump_3b.ogg",
		"media/click_tap.m4a",
		"media/click_tap.ogg",
		"media/twinz_being_removed.m4a",
		"media/twinz_being_removed.ogg",
		"media/super jump_01.m4a",
		"media/super jump_01.ogg",
		"media/tap_04.m4a",
		"media/tap_04.ogg",
		"media/tap_on_good_pair_1.m4a",
		"media/tap_on_good_pair_1.ogg",
		"media/tap_on_good_pair_2.m4a",
		"media/tap_on_good_pair_2.ogg",
		"media/tap_on_good_pair_3.m4a",
		"media/tap_on_good_pair_3.ogg",
		"media/tap_on_good_pair_4.m4a",
		"media/tap_on_good_pair_4.ogg",
		"media/tap_on_good_pair_5.m4a",
		"media/tap_on_good_pair_5.ogg",
		"media/jeszcze lepsza muzyka do twinz.m4a",
		"media/jeszcze lepsza muzyka do twinz.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ga_init.js"
	]
}