function k(b,a,c,d){b.v.Fb(b.lb,a,c,d)}function l(b,a,c,d){b.v.ca?k(b,a,c,d):b.v.De()._OnMessageFromDOM({type:"event",component:b.lb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.C(b.lb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Rb||(b.v.qd(b.Wd),b.Rb=!0)}window.La=class{constructor(b,a){this.v=b;this.lb=a;this.Rb=!1;this.Wd=()=>this.Oa()}ed(){}Oa(){}};
window.kf=class{constructor(){this.bd=-1}j(){-1!==this.bd&&(self.clearTimeout(this.bd),this.bd=-1)}};"use strict";class aa{constructor(b){this.Jc=b;this.Mc=!1;this.Tc=!0}}function ba(b,a){const c=a.elementId,d=b.jd(a),e=new aa(d);b.ob.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Tc=!!a.isVisible;d.addEventListener("focus",()=>{ca(b,"elem-focused",c)});d.addEventListener("blur",()=>{ca(b,"elem-blurred",c)});b.Nb&&document.body.appendChild(d)}
function v(b,a,c){n(b,a,d=>{const e=w(b,d.elementId);return c(e,d)})}function w(b,a){b=b.ob.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Jc}function ca(b,a,c){var d;d||(d={});d.elementId=c;k(b,a,d)}
window.oe=class extends self.La{constructor(b){super(b,"iframe");this.ob=new Map;this.Nb=!0;t(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=w(this,a);this.ld(c);this.Nb&&c.parentElement.removeChild(c);this.ob.delete(a)}],["set-visible",a=>{if(this.Nb){var c=this.ob.get(a.elementId),d=c.Jc;c.Mc?d.style.display=a.isVisible?"":"none":c.Tc=!!a.isVisible}}],["update-position",a=>{if(this.Nb){var c=this.ob.get(a.elementId),d=c.Jc;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Mc||(c.Mc=!0,c.Tc&&(d.style.display=""))}}],["update-state",a=>{w(this,a.elementId);this.pd()}],["focus",a=>this.Cc(a)],["set-css-style",a=>{const c=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);v(this,"get-element",
a=>a)}jd(){throw Error("required override");}ld(){}pd(){throw Error("required override");}Cc(b){var a=w(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let fa=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.$e?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.df+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ha=!1,ia=!1;function ja(){if(!ha){try{new Worker("blob://",{get type(){ia=!0}})}catch(b){}ha=!0}return ia}let C=new Audio;
const ka={"audio/webm; codecs=opus":!!C.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!C.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!C.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!C.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!C.canPlayType("audio/mp4"),"audio/mpeg":!!C.canPlayType("audio/mpeg")};C=null;async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}
function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const E=[];let F=0;window.RealFile=window.File;const G=[],H=new Map,qa=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.oa=class b{constructor(a){this.ca=a.ff;this.wa=null;this.ba="";this.ab=a.cf;this.Cb={};this.Ua=this.ua=null;this.Pb=[];this.J=this.xa=null;this.Qc=!1;this.Dd=0;this.rb=null;this.$a=-1;this.Ve=()=>this.Ke();this.Za=[];this.u=a.Xd;this.Tb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ja()||(this.ca=!1);this.ca&&ea&&(this.ca=!1);if("playable-ad"===this.u||"instant-games"===this.u)this.ca=!1;if("cordova"===this.u&&this.ca)if(y){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Wb=this.ra=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.Ge(c));this.C("runtime","create-job-worker",()=>this.He());"cordova"===this.u?document.addEventListener("deviceready",
()=>this.td(a)):this.td(a)}j(){this.uc();this.wa&&(this.wa=this.wa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Ua&&(this.Ua.j(),this.Ua=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}se(){return da&&"cordova"===this.u}qc(){const a=navigator.userAgent;return da&&ta.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}qe(){return y}md(){return y&&ta.has(this.u)}async td(a){"macos-wkwebview"===this.u&&this.Fc({type:"ready"});if("playable-ad"===
this.u){this.ra=self.c3_base64files;this.Wb={};await this.ze();for(let d=0,e=a.cb.length;d<e;++d){var c=a.cb[d];this.Wb.hasOwnProperty(c)?a.cb[d]={$e:!0,df:this.Wb[c]}:this.ra.hasOwnProperty(c)&&(a.cb[d]=URL.createObjectURL(this.ra[c]))}a.jc=[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.qd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.bf?this.ba=a.bf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),
-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.hf&&(this.Cb=a.hf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Je(d));this.rb=new self.te(this);await va(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.Fe(a,c.port2):await this.Ee(a,c.port2)}wc(a){a=this.Cb.hasOwnProperty(a)?this.Cb[a]:a.endsWith("/workermain.js")&&this.Cb.hasOwnProperty("workermain.js")?this.Cb["workermain.js"]:"playable-ad"===this.u&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async lc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Tb)return a=await this.Db(d.Ze?a:this.ab+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}sd(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ha(),g=window.devicePixelRatio,h=b.hb(),m=a.qf,p=window.cr_previewImageBlobs||this.ra,q=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.nf||
"";a=a.Xd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.rb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.pf,jobScheduler:{inputPort:B.Pc,outputPort:B.Xc,maxNumWorkers:B.Se},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ab+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.ab+"opus.wasm.wasm",isFileProtocol:this.Tb,isiOSCordova:this.se(),isiOSWebView:this.qc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Fe(a,c){const d=this.wc(a.gf);"preview"===this.u?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const p=q=>{this.ua.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():m()};this.ua.addEventListener("message",p);this.ua.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ua=await this.lc(d,this.ba,{type:"module",name:"Runtime",Ze:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.jc||[],g=a.cb;f=await Promise.all(f.map(h=>this.Pa(h)));g=await Promise.all(g.map(h=>this.Pa(h)));if("cordova"===this.u)for(let h=0,m=a.ic.length;h<m;++h){const p=
a.ic[h],q=p[0];if(q===a.cd||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Pa(q)}this.ua.postMessage(Object.assign(this.sd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ic,mainProjectScript:a.cd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...wa(this.rb)]);this.Pb=G.map(h=>new h(this));this.rd();xa(this.xa);self.c3_callFunction=(h,m)=>{var p=this.xa;return p.v.od(p.lb,"js-invoke-function",
{name:h,params:m})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.Fb("runtime","go-to-last-error-script"))}async Ee(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Pb=G.map(g=>new g(this));this.rd();var d=a.cb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.jc)){var e=[...a.jc].map(g=>g instanceof Blob?URL.createObjectURL(g):
g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Pa(g)));await Promise.all(d.map(g=>z(g)));d=self.C3_ProjectScriptsStatus;e=a.cd;const f=a.ic;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Pa(h),await z(h),"preview"!==this.u||d[g]||this.vd(g,"main script did not run to completion")}catch(m){this.vd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Pa(h),await z(h);"preview"===this.u&&"object"!==typeof self.jf.lf?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.sd(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:sa}),xa(this.xa),this.ud(),this.Ua=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ua,a))}vd(a,c){this.Jb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ud(){this.Jb()}Jb(){const a=
window.Xe;a&&(a.parentElement.removeChild(a),window.Xe=null)}async He(){const a=await ya(this.rb);return{outputPort:a,transferables:[a]}}De(){if(this.ca)throw Error("not available in worker mode");return this.Ua}Fb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}od(a,c,d,e,f){const g=ra++,h=new Promise((m,p)=>{qa.set(g,{resolve:m,reject:p})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ie(a);if("result"===c)this.Le(a);else if("runtime-ready"===c)this.Me();else if("alert-error"===c)this.Jb(),alert(a.message);else if("creating-runtime"===c)this.ud();else throw Error(`unknown message '${c}'`);}Ie(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=H.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Ib(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Ib(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Ib(f,!1,""+h)}):this.Ib(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Ib(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Le(a){const c=a.responseId,d=a.isOk;a=a.result;const e=qa.get(c);d?e.resolve(a):e.reject(a);qa.delete(c)}C(a,
c,d){let e=H.get(a);e||(e=new Map,H.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ka(a){if(G.includes(a))throw Error("DOM handler already added");G.push(a)}rd(){for(const a of this.Pb)if("runtime"===a.lb){this.xa=a;return}throw Error("cannot find runtime DOM handler");}Je(a){this.Fb("debugger","message",a)}Me(){for(const a of this.Pb)a.ed()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
ua)}static Kb(a){ua=!!a}qd(a){this.Za.push(a);this.Ec()}Oe(a){a=this.Za.indexOf(a);if(-1===a)throw Error("invalid callback");this.Za.splice(a,1);this.Za.length||this.uc()}Ec(){-1===this.$a&&this.Za.length&&(this.$a=requestAnimationFrame(this.Ve))}uc(){-1!==this.$a&&(cancelAnimationFrame(this.$a),this.$a=-1)}Ke(){this.$a=-1;for(const a of this.Za)a();this.Ec()}Ca(a){this.xa.Ca(a)}Na(a){this.xa.Na(a)}Dc(){this.xa.Dc()}Hb(a){this.xa.Hb(a)}re(){return!!ka["audio/webm; codecs=opus"]}async Pe(a){a=await this.od("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ve(a){this.Qc=!0;this.Dd=a}pe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}nd(a){return!this.pe(a)}async Pa(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Tb&&this.nd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Db(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ge(a){const c=a.filename;switch(a.as){case "text":return await this.ne(c);
case "buffer":return await this.Db(c);default:throw Error("unsupported type");}}hd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ne(a){a=await this.hd(a);return await la(a)}vc(){if(E.length&&!(8<=F)){F++;var a=E.shift();this.Ae(a.filename,a.ef,a.Ye)}}Db(a){return new Promise((c,d)=>{E.push({filename:a,ef:e=>{F--;this.vc();c(e)},Ye:e=>{F--;this.vc();d(e)}});this.vc()})}async Ae(a,c,d){try{const e=
await this.hd(a),f=await ma(e);c(f)}catch(e){d(e)}}Fc(a){if("windows-webview2"===this.u)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.u)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ze(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.ye(c,d));await Promise.all(a)}async ye(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Wb[a]=c.str;else{let d=
await this.Ce(c);d||(d=this.Be(c));this.ra[a]=d}}async Ce(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Be(a){a=this.Ne(a);return this.xe(a.data,a.af)}Ne(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{af:a,data:d}}xe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const I=self.oa;
function za(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},Ca={dispatchRuntimeEvent:!0};
function Da(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ea(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}
function Fa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ga(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Fa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function xa(b){b.Cd=!0;b.Uc=b.v.pa();b.sb=b.v.ha()}async function Na(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Oa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Pa(b){return await self.C3_GetSvgImageSize(b.blob)}function Qa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ra(b){self.setTimeout(()=>{b.Bd=!0},1E3);"cordova"===b.v.u?(document.addEventListener("pause",()=>Sa(b,!0)),document.addEventListener("resume",()=>Sa(b,!1))):document.addEventListener("visibilitychange",()=>Sa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ma)}}
function Ta(b){b.xd||(b.xd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Ua(b){b.wd||(b.wd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Va(b){await Da(b.url)}
function Wa(b,a){b.Ed=a.message;-1===b.Kc&&(b.Kc=setTimeout(()=>{b.Kc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ed)},250))}function M(b){if(!b.$){var a=I.hb();a&&"any"!==b.$c&&Xa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ha()})}}function Ya(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.hb(),innerWidth:b.pa(),innerHeight:b.ha()})}
function Sa(b,a){a?b.v.uc():b.v.Ec();k(b,"visibilitychange",{hidden:a})}function Za(b,a,c){"Backspace"===c.key&&L(c);if(!b.$){var d=Aa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}
function $a(b,a,c,d){b.$||za(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function ab(b){window!==window.top&&window.focus();bb(b.target)&&document.activeElement&&!bb(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.xb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),$a(b,d,c,Ba),b.xb=c.buttons)}}
function cb(b,a,c){if(!b.$&&!za(c)){var d=b.xb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.xb=c.buttons;$a(b,c.type,c,Ba)}}
function O(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function db(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function fb(b,a,c,d){const e=b.pa(),f=b.ha();b.bb=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.hb()}):10>d&&gb(b,e,f,d+1)}
function gb(b,a,c,d){-1!==b.bb&&clearTimeout(b.bb);b.bb=setTimeout(()=>fb(b,a,c,d),48)}
function Xa(b){b=b.$c;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function bb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.Ka(class extends self.La{constructor(b){super(b,"runtime");this.Jd=!0;this.Cd=!1;this.bb=-1;this.$c="any";this.wd=this.xd=!1;this.ec=document.createElement("div");this.ec.className="c3-screen-reader-text";this.ec.setAttribute("aria-live","polite");document.body.appendChild(this.ec);this.Fa=null;this.$=!1;this.Ed="";this.Kc=-1;this.Bd=!1;this.Uc=b.pa();this.sb=b.ha();this.da=this.Bb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Qc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Jd&&(e.style.display="",this.Jd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Na(d));b.C("runtime","raster-svg-image",d=>Oa(d));b.C("runtime","get-svg-image-size",
d=>Pa(d));b.C("runtime","set-target-orientation",d=>{this.$c=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Qa(d));b.C("runtime","go-to-script",d=>Qa(d));b.C("runtime","before-start-ticking",()=>Ra(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Fa||(this.Fa=document.createElement("div"),this.Fa.id="inspectOutline",document.body.appendChild(this.Fa));var e=this.Fa;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Fa&&(this.Fa.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ta(this));b.C("runtime","enable-device-motion",()=>Ua(this));b.C("runtime","add-stylesheet",d=>Va(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.zc(d));b.C("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ec.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.ve(d.duration)});b.C("runtime","export-to-video-progress",d=>Wa(this,d));b.C("runtime","exported-to-video",d=>{window.We({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.We({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ha(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",
L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.xb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ka,{passive:!1});window.addEventListener("wheel",Ka,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Cd){var d=this.pa();var e=this.ha();if(this.v.md()){if(this.Bd){if(this.Uc===
d&&e<this.sb){this.Bb=this.sb-e;db(this,this.sb,this.Bb);d=void 0;break a}0<this.Bb&&(this.Bb=0,db(this,e,this.Bb))}this.Uc=d;this.sb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.hb()});this.v.qc()&&(-1!==this.bb&&clearTimeout(this.bb),fb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",()=>
M(this));window.addEventListener("fullscreenerror",d=>Ya(this,d));window.addEventListener("webkitfullscreenerror",d=>Ya(this,d));window.addEventListener("mozfullscreenerror",d=>Ya(this,d));if(b.qc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ha(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(I.Kb(!0),M(this)):"exited-fullscreen"===d?(I.Kb(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Va=new Set;this.Yb=new WeakSet;this.va=!1}ed(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Ca)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}k(this,"window-blur",{parentHasFocus:a},Ca);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&k(this,"keyboard-blur",null,Ca)});window.addEventListener("keydown",a=>Za(this,"keydown",a));window.addEventListener("keyup",a=>Za(this,"keyup",a));window.addEventListener("dblclick",a=>$a(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{ab(a);N(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{ab(a);cb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>cb(this,"pointermove",a)),window.addEventListener("mouseup",a=>cb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{ab(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=
()=>this.Dc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.qe()&&!this.v.md()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{db(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.v.pa()}ha(){return this.v.ha()}Dc(){var b=
[...this.Va];this.Va.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Yb.has(a)||this.Va.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.Yb.delete(b);let a;try{a=b.play()}catch(c){this.Va.add(b);return}a&&a.catch(()=>{this.Yb.has(b)||this.Va.add(b)})}Na(b){this.Va.delete(b);this.Yb.add(b)}Hb(b){this.va=!!b}zc(b){alert(b.message)}});"use strict";
async function va(b){if(b.Qe)throw Error("already initialised");b.Qe=!0;var a=b.ya.wc(("playable-ad"===b.ya.u?b.ya.ab:"")+"dispatchworker.js");b.Ic=await b.ya.lc(a,b.kb,{name:"DispatchWorker"});a=new MessageChannel;b.Pc=a.port1;b.Ic.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Xc=await ya(b)}function wa(b){return[b.Pc,b.Xc]}
async function ya(b){const a=b.Kd.length;var c=b.ya.wc(("playable-ad"===b.ya.u?b.ya.ab:"")+"jobworker.js");c=await b.ya.lc(c,b.kb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Ic.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Kd.push(c);return e.port1}
self.te=class{constructor(b){this.ya=b;this.kb=b.ba;this.kb="preview"===b.u?this.kb+"workers/":this.kb+b.ab;this.Se=Math.min(navigator.hardwareConcurrency||2,16);this.Ic=null;this.Kd=[];this.Xc=this.Pc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.oa({ff:!1,gf:"workermain.js",cb:["scripts/c3runtime.js"],ic:[],cd:"",cf:"scripts/",jc:[],Xd:"html5"}));"use strict";
async function hb(b,a){a=a.type;let c=!0;0===a?c=await ib():1===a&&(c=await jb());k(b,"permission-result",{type:a,result:c})}async function ib(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function jb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.oa.Ka(class extends self.La{constructor(b){super(b,"touch");n(this,"request-permission",a=>hb(this,a))}});"use strict";function kb(b,a,c){lb(b,a,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));b.Sb=!0}
function lb(b,a,c){a.src&&a.src.startsWith("blob:")&&b.Sb&&URL.revokeObjectURL(a.src);a.src=c}
self.oa.Ka(class extends self.oe{constructor(b){super(b);this.Sb=!1;v(this,"navigate-url",(a,c)=>{lb(this,a,c.url);this.Sb=!1});v(this,"display-html",(a,c)=>kb(this,a,c))}jd(b){const a=document.createElement("iframe");a.style.position="absolute";a.style.border="none";var c=navigator.userAgent;/iphone|ipad|ipod/i.test(c)&&(c=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(c),c=parseInt(c[c.length-1]),12>=c||isNaN(c))&&(a.setAttribute("noresize","noresize"),a.setAttribute("scrolling","no"));b.isVisible||
(a.style.display="none");b.id&&(a.id=b.id);b.allow&&(a.setAttribute("allow",b.allow),b.allow.includes("fullscreen")&&a.setAttribute("allowfullscreen",""));b.enableSandbox&&a.setAttribute("sandbox",b.sandbox);b.url?a.src=b.url:b.html&&kb(this,a,b);return a}pd(){}ld(b){lb(this,b,"");this.Sb=!1}});"use strict";function mb(){}function nb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function ob(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.oa.Ka(class extends self.La{constructor(b){super(b,"browser");this.u="";t(this,[["get-initial-state",a=>this.Bc(a)],["ready-for-sw-messages",()=>nb(this)],["alert",a=>this.zc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Cc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ob(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.mf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.oa.Kb(!0),
this.v.Fc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(mb)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.oa.Kb(!1),this.v.Fc({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(mb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}Bc(b){this.u=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}zc(b){alert(b.message)}Cc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";const pb=180/Math.PI;
async function qb(b,a){if(a.isiOSCordova||a.isSafari)b.ac=!0;b.ad=a.timeScaleMode;b.Pd=["equalpower","HRTF","soundfield"][a.panningModel];b.Ad=["linear","inverse","exponential"][a.distanceModel];b.Qd=a.refDistance;b.Od=a.maxDistance;b.Sd=a.rolloffFactor;if(b.v.Qc)b.ac=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.Dd)});else{var c={latencyHint:a.latencyHint};b.Vd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");rb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&rb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ra=b.g.createGain();b.Ra.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function sb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Ld=g.slice(0);tb(b,g);try{b.R=await ub(b,c,d,e,g,f);if(q){Q(b.R,!0);var r=b.R,B=q.innerAngle,na=q.outerAngle,pa=q.outerGain;if(r.qb){vb(r,q.x,q.y,q.z,q.angle);var D=self.eb.we;r.sa[0]!==D(B)&&
(r.sa[0]=D(B),r.F.coneInnerAngle=D(B));r.sa[1]!==D(na)&&(r.sa[1]=D(na),r.F.coneOuterAngle=D(na));r.sa[2]!==pa&&(r.sa[2]=pa,r.F.coneOuterGain=pa)}q.hasOwnProperty("uid")&&(b.R.qa=q.uid)}else"number"===typeof A&&0!==A?(R(b.R,!0),wb(b.R,A)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,m,p,x)}catch(Jb){console.error("[Construct] Audio: error starting playback: ",Jb);return}finally{c=g.join(" ");d=b.zb.get(c);if(!d)throw Error("expected pending tag");d.dd--;0===d.dd&&(d.resolve(),b.zb.delete(c))}u(b)}
async function xb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await yb(b,c);for(const h of S(b,c))if(!h.Ta){c=h.G.gain;c.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ja=d;h.Sa=g;h.Ud=a}T(b)}async function zb(b,a){const c=a.tags;a=a.rate;await yb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Da())}async function Ab(b,a){const c=a.tags;a=a.pos;await yb(b,c);for(const d of S(b,c))d.rc(a)}
async function Bb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ub(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Cb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function Db(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.ce(b,...e);else if("delay"===c)d=new self.ae(b,...e);else if("convolution"===c){var g=d=new self.$d(b,f.ia,...e),h=a.bufferType;g.yd=a.bufferOriginalUrl;g.zd=h}else if("flanger"===c)d=new self.de(b,...e);else if("phaser"===
c)d=new self.fe(b,...e);else if("gain"===c)d=new self.ee(b,...e);else if("stereopan"===c)d=new self.he(b,...e);else if("tremolo"===c)d=new self.ie(b,...e);else if("ringmod"===c)d=new self.ge(b,...e);else if("distortion"===c)d=new self.be(b,...e);else if("compressor"===c)d=new self.Zd(b,...e);else if("analyser"===c)d=new self.Yd(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let p=g.ka.get(h);p||(p=[],g.ka.set(h,p));d.Id=p.length;d.Zc=h;p.push(d);Eb(g,h)}Fb(b)}
async function Gb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.fc=a.timeScale;b.Lc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.va=a.isSilent;b.v.Hb(b.va);b.Xb=a.masterVolume;b.Ra.gain.value=
b.Xb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Db(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Hb(b,f,c)));T(b)}
async function Ib(b,a){try{const c=b.g.suspend(a.time);b.Hd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Fb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Kb(d)),b.Hd=!0);await c}catch(c){Kb(c)}}
function rb(b){b.Qb||(b.Oc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Qb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.gb()===c)return await Lb(g),g;if(f)return null;if(e&&(b.ac||b.Gd)){f=0;for(let h=0,m=b.ja.length;h<m;++h)g=b.ja[h],b.ja[f]=g,g.Aa()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.Vd;e&&f&&(b.Gd=!0);c=!e||b.ac||f?new self.le(b,a,c,d,e,f):new self.je(b,a,c,d,e);b.ja.push(c);await Lb(c);b.Nd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Nd.add(a));return c}
function Mb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Nb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.na()}function Eb(b,a){a=a.toLowerCase();let c=b.na();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.na()):e.U(d[f+1].N())}}for(const f of Ob(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ga&&b.Vc===a&&(b.Ga.disconnect(),b.Ga.connect(c))}
function*Ob(b,a){if(a)for(const c of b.H)Mb(0<c.ma.length?c.ma[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Pb(b,a,c){return c?b.v.Pe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Qb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.ma;var c=a;for(const e of c){c=!1;for(const f of b)if(Mb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function ub(b,a,c,d,e,f){for(const g of b.H)if(g.gb()===c&&(g.kc()||f))return g.ma=e,g;a=await P(b,a,c,d,f);e="html5"===a.Gc?new self.ke(a.s,a,e):new self.me(a.s,a,e);b.H.push(e);return e}
function tb(b,a){a=a.join(" ");let c=b.zb.get(a);if(!c){let d=null;c={dd:0,promise:new Promise(e=>d=e),resolve:d};b.zb.set(a,c)}c.dd++}function yb(b,a){return(b=b.zb.get((0===a.length?b.Ld:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Qa.size)u(b);else for(const a of b.H)if(!a.I&&!a.O()){u(b);break}}function Rb(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function Fb(b){b.Rc||(b.Rc=!0,Promise.resolve().then(()=>Sb(b)))}
function Sb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.fb());k(b,"fxstate",{fxstate:a});b.Rc=!1}
async function Hb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ub(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],f=d.orient,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],e.setPosition(...b.Xa),e.setOrientation(...b.Wa),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),wb(b,d));c.Play(m,p,q,0);a.isPlaying||c.ib();c.yc(a)}}}function Kb(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.La{constructor(b){super(b,"audio");this.Ra=this.g=null;this.Qb=this.Oc=!1;this.za=()=>{if(!this.Oc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Qb&&(this.Oc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Qb=!1)}};this.ja=[];this.H=[];this.R=null;this.Ld=[];this.Nd=new Set;this.Md=-1;this.zb=new Map;this.Xb=1;this.va=!1;this.ad=0;this.fc=1;this.Lc=0;this.Pd="HRTF";this.Ad="inverse";this.Qd=600;this.Od=1E4;this.Sd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Gd=this.ac=!1;this.Vd=this.v.re();this.ka=new Map;this.Qa=new Set;this.Hd=this.Rc=!1;this.Vc="";this.Ga=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ga&&this.Ga.disconnect();this.Vc=c.toLowerCase();this.Ga=this.g.createMediaStreamSource(a);
this.Ga.connect(Nb(this,this.Vc))};this.Ob=null;self.C3Audio_GetOutputStream=()=>{this.Ob||(this.Ob=this.g.createMediaStreamDestination(),this.Ra.connect(this.Ob));return this.Ob.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>qb(this,a)],["play",a=>sb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ib():d.Gb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>xb(this,a)],["set-master-volume",a=>{this.Xb=a.vol;this.Ra.gain.value=this.Xb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Tb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.v.Hb(this.va);for(const c of this.H)c.Lb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.sc(a)}],["set-playback-rate",a=>zb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),wb(d,a)}],["seek",a=>Ab(this,a)],["preload",a=>Bb(this,a)],["unload",a=>Cb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.tc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Db(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Fb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);Eb(this,a)}}],["tick",a=>{this.fc=a.timeScale;this.Lc=a.gameTime;this.Md=a.tickCount;if(0!==this.ad)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&vb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Gb(this,a)],["offline-render-audio",a=>Ib(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}na(){return this.Ra}Eb(){return this.va}Ca(b){this.v.Ca(b)}Na(b){this.v.Na(b)}Oa(){for(var b of this.Qa)b.Oa();
b=this.g.currentTime;for(var a of this.H)a.Oa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.fb());k(this,"state",{tickCount:this.Md,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Qa].map(c=>({tag:c.Zc,index:c.Id,peak:c.Ya,rms:c.Rd,binCount:c.l.frequencyBinCount,freqBins:c.Fd}))});0===a.length&&0===this.Qa.size&&this.Rb&&(this.v.Oe(this.Wd),this.Rb=!1)}static we(b){return b*pb}static kd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ue(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.oa.Ka(self.eb);"use strict";function Lb(b){b.Vb||(b.Vb=b.xc());return b.Vb}self.fd=class{constructor(b,a,c,d,e){this.s=b;this.Ue=a;this.Ia=c;this.T=d;this.Re=e;this.Gc="";this.Vb=null}j(){this.Vb=this.s=null}xc(){}W(){return this.s.W()}nc(){return this.Ue}gb(){return this.Ia}mc(){return this.T}Aa(){return this.Re}ga(){}};"use strict";
self.je=class extends self.fd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Gc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.W().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.W().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ia}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Qb(this.s,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}xc(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ia})}V(){return this.M}ga(){return this.M.duration}};"use strict";
async function Ub(b){if(b.Ea)return b.Ea;var a=b.s.v;if("cordova"===a.u&&a.nd(b.Ia)&&a.Tb)b.Ea=await a.Db(b.Ia);else{a=await fetch(b.Ia);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ea=await a.arrayBuffer()}}async function Vb(b){if(b.ia)return b.ia;b.ia=await Pb(b.s,b.Ea,b.Te);b.Ea=null}
self.le=class extends self.fd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Gc="webaudio";this.ia=this.Ea=null;this.Te=!!f}j(){Qb(this.s,this);this.ia=this.Ea=null;super.j()}async xc(){try{await Ub(this),await Vb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ia}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Wb=0;
function Q(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(R(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.s.Pd,b.F.distanceModel=b.s.Ad,b.F.refDistance=b.s.Qd,b.F.maxDistance=b.s.Od,b.F.rolloffFactor=b.s.Sd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Ub!==a&&(b.Ub=a,b.Ub?(Q(b,!1),b.fa=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function wb(b,a){b.Ub&&b.Yc!==a&&(b.fa.pan.value=a,b.Yc=a)}function U(b,a){b.Ja=a;b.G.gain.cancelScheduledValues(0);b.Sa=-1;b.G.gain.value=b.oc()}function Tb(b,a){a=!!a;b.Ta!==a&&(b.Ta=a,b.Lb())}
function vb(b,a,c,d,e){if(b.qb){var f=b.Xa,g=b.Wa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Sc?b.s.Lc:performance.now()/1E3}
self.gd=class{constructor(b,a,c){this.s=b;this.P=a;this.ma=c;this.Mb=Wb++;this.G=this.W().createGain();this.G.connect(this.na());this.F=null;this.qb=!1;this.Xa=[0,0,0];this.Wa=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Ub=!1;this.Yc=0;this.I=!0;this.Y=this.ta=this.K=!1;this.Ja=1;this.Ta=!1;this.la=1;b=this.s.ad;this.Sc=1===b&&!this.Aa()||2===b;this.Sa=this.qa=-1;this.Ud=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}W(){return this.s.W()}na(){return Nb(this.s,0<this.ma.length?this.ma[0]:"")}nc(){return this.P.nc()}gb(){return this.P.gb()}mc(){return this.P.mc()}Aa(){return this.P.Aa()}O(){}kc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}Ma(){}ga(){return this.P.ga()}Play(){}Ba(){}ib(){}Gb(){}Oa(b){-1!==this.Sa&&b>=this.Sa&&(this.Sa=-1,this.Ud&&this.Ba(),Rb(this.s,"fade-ended",this.ma,this.Mb))}oc(){const b=this.Ja;return isFinite(b)?b:0}Eb(){return this.s.Eb()}Lb(){}sc(){}Da(){}rc(){}tc(){}pc(){}fb(){var b=
this.Mb,a=this.ma,c=this.ga(),d=-1===this.Sa?this.Ja:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Xa,orient:this.Wa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ma(),playbackRate:this.la,uid:this.qa,bufferOriginalUrl:this.nc(),bufferUrl:"",bufferType:this.mc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.Ta,resumePosition:this.pc(),pan:f,stereoPan:this.fa?
this.Yc:null}}yc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Tb(this,b.isMuted)}};"use strict";
self.ke=class extends self.gd{constructor(b,a,c){super(b,a,c);this.P.yb.connect(this.G);this.P.onended=()=>this.Ac()}j(){this.Ba();this.P.yb.disconnect();super.j()}V(){return this.P.V()}Ac(){this.I=!0;this.qa=-1;Rb(this.s,"ended",this.ma,this.Mb)}O(){return this.V().ended}kc(){return this.I?!0:this.O()}Ma(){let b=this.V().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.V();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.gb()}' to position '${c}': `,e)}this.s.Ca(d);this.K=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.V();b.paused||b.pause();this.s.Na(b);this.I=!0;this.K=!1;this.qa=-1}ib(){if(!(this.K||this.I||this.O())){var b=this.V();b.paused||b.pause();this.s.Na(b);this.K=!0}}Gb(){!this.K||this.I||this.O()||(this.s.Ca(this.V()),this.K=!1)}Lb(){this.V().muted=this.Ta||this.Eb()}sc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.V().loop=b)}Da(){let b=this.la;this.Sc&&(b*=this.s.fc);try{this.V().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}rc(b){if(!this.I&&!this.O())try{this.V().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}pc(){return this.Ma()}tc(b){b?this.IsPlaying()?(this.V().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.s.Ca(this.V()),this.ta=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.jb=null}
self.me=class extends self.gd{constructor(b,a,c){super(b,a,c);this.o=null;this.Zb=d=>this.Ac(d);this.Nc=!0;this.jb=null;this.S=this.$b=this.bc=0;this.Wc=1}j(){this.Ba();W(this);this.Zb=null;super.j()}Ac(b){this.K||this.ta||b.target!==this.jb||(this.I=this.Nc=!0,this.qa=-1,W(this),Rb(this.s,"ended",this.ma,this.Mb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Nc}kc(){return!this.o||this.I?!0:this.O()}Ma(){let b;b=this.K?this.S:this.$b+(V(this)-this.bc)*this.la;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Wc=1;U(this,a);W(this);this.o=this.W().createBufferSource();this.o.buffer=this.P.ia;this.o.connect(this.G);this.jb=this.o;this.o.onended=this.Zb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Nc=!1;this.Y=b;this.la=1;this.bc=V(this);this.$b=c}Ba(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.qa=-1}ib(){this.K||this.I||this.O()||(this.S=this.Ma(),this.Y&&(this.S%=this.ga()),this.K=!0,this.o.stop(0))}Gb(){!this.K||this.I||this.O()||(W(this),this.o=
this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.Zb,this.o.loop=this.Y,U(this,this.Ja),this.Da(),this.o.start(0,this.S),this.bc=V(this),this.$b=this.S,this.K=!1)}oc(){return super.oc()*this.Wc}Lb(){this.Wc=this.Ta||this.Eb()?0:1;U(this,this.Ja)}sc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Da(){let b=this.la;this.Sc&&(b*=this.s.fc);this.o&&(this.o.playbackRate.value=b)}rc(b){this.I||this.O()||(this.K?this.S=b:(this.ib(),this.S=
b,this.Gb()))}pc(){return this.S}tc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.Ma(),this.Y&&(this.S%=this.ga()),this.o.stop(0)):this.ta=!1:this.ta&&(W(this),this.o=this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.Zb,this.o.loop=this.Y,U(this,this.Ja),this.Da(),this.o.start(0,this.S),this.bc=V(this),this.$b=this.S,this.ta=!1)}yc(b){super.yc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.W();this.Id=-1;this.T=this.Zc="";this.m=null}j(){this.g=null}N(){}U(){}fb(){return{type:this.T,tag:this.Zc,params:this.m}}}
self.ce=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ae=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.vb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.nb=X(this);this.nb.gain.value=c;this.A.connect(this.vb);this.A.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.X);this.X.connect(this.nb);this.nb.connect(this.vb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.X.disconnect();this.nb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.eb.kd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.nb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.$d=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.zd=this.yd="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.mb=this.g.createConvolver();this.mb.normalize=c;this.mb.buffer=a;this.A.connect(this.mb);this.A.connect(this.h);this.mb.connect(this.i)}j(){this.A.disconnect();this.mb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.yd;b.bufferUrl="";b.bufferType=this.zd;return b}};
self.de=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.pb=X(this);this.pb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.pb);this.pb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.pb.gain,a/100,c,d)}}};
self.fe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.ee=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.eb.kd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.he=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ie=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ge=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Ab=X(this);this.Ab.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Ab.gain);this.B.start(0);this.A.connect(this.Ab);this.A.connect(this.h);this.Ab.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Ab.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.be=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=X(this);this.dc=X(this);this.cc=X(this);b=d;.01>b&&(b=.01);this.dc.gain.value=b;this.cc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.hc=this.g.createWaveShaper();this.Hc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Hc[32768+e]=f,this.Hc[32768-
e-1]=-f;this.hc.curve=this.Hc;this.A.connect(this.dc);this.A.connect(this.h);this.dc.connect(this.hc);this.hc.connect(this.cc);this.cc.connect(this.i)}j(){this.A.disconnect();this.dc.disconnect();this.hc.disconnect();this.cc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Zd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Yd=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Fd=new Float32Array(this.l.frequencyBinCount);this.Td=new Uint8Array(a);this.Rd=this.Ya=0;b=this.s;b.Qa.add(this);T(b)}j(){this.s.Qa.delete(this);this.l.disconnect();super.j()}Oa(){this.l.getFloatFrequencyData(this.Fd);this.l.getByteTimeDomainData(this.Td);const b=this.l.fftSize;let a=this.Ya=0;for(var c=0;c<b;++c){let d=(this.Td[c]-
128)/128;0>d&&(d=-d);this.Ya<d&&(this.Ya=d);a+=d*d}c=self.eb.ue;this.Ya=c(this.Ya);this.Rd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Xb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function Yb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Zb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function $b(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function ac(b){if(!b.Ha)try{b.Ha=await navigator.wakeLock.request("screen"),b.Ha.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ha=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
async function bc(b){const a=await cc();k(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function cc(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Xb(b),Yb(b),Zb(b),$b(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.oa.Ka(class extends self.La{constructor(b){super(b,"platform-info");t(this,[["get-initial-state",()=>this.Bc()],["request-wake-lock",()=>ac(this)],["release-wake-lock",()=>{this.Ha&&(this.Ha.release(),this.Ha=null)}]]);window.addEventListener("resize",()=>bc(this));this.Ha=null}async Bc(){const b=await cc();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});
