{
	"version": 1576602522,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/btnbacktomain-sheet0.png",
		"images/btnbacktomain-sheet1.png",
		"images/btnbacktomain-sheet2.png",
		"images/btnsoundunmute-sheet0.png",
		"images/btnsoundunmute-sheet1.png",
		"images/btnsoundunmute-sheet2.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundmute-sheet1.png",
		"images/btnsoundmute-sheet2.png",
		"images/btnplay-sheet0.png",
		"images/btnplay-sheet1.png",
		"images/btnplay-sheet2.png",
		"images/btnrewardad-sheet0.png",
		"images/btnswitchgame-sheet0.png",
		"images/btnswitchgame-sheet1.png",
		"images/logoblackmoon-sheet0.png",
		"images/pausecurtain.png",
		"images/preloaderfont2.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/gameplaybackground1-sheet0.png",
		"images/coverbackground-sheet0.png",
		"images/scorepanel-sheet0.png",
		"images/btnpause-sheet0.png",
		"images/btnpause-sheet1.png",
		"images/btnpause-sheet2.png",
		"images/pausedcurtain-sheet0.png",
		"images/newbesthighscore-sheet0.png",
		"images/highscorelabel-sheet0.png",
		"images/bmlogo-sheet0.png",
		"images/board-sheet0.png",
		"images/logo-sheet0.png",
		"images/popupcurtain-sheet0.png",
		"images/btnrestart-sheet0.png",
		"images/btnrestart-sheet1.png",
		"images/btnrestart-sheet2.png",
		"images/stol-sheet0.png",
		"images/pilka-sheet0.png",
		"images/recttest-sheet0.png",
		"images/sprezyna-sheet0.png",
		"images/recttestanch-sheet0.png",
		"images/grzybek_6-sheet0.png",
		"images/grzybek_6-sheet1.png",
		"images/hitcircle-sheet0.png",
		"images/odbijacz_lewy-sheet0.png",
		"images/odbijacz_prawy-sheet0.png",
		"images/licznikzyc-sheet0.png",
		"images/tryagain-sheet0.png",
		"images/flashscreen-sheet0.png",
		"images/howtoplay-sheet0.png",
		"images/howtoplay-sheet1.png",
		"images/htp_touch_-sheet0.png",
		"images/htp_touch_-sheet1.png",
		"images/bouncer-sheet0.png",
		"images/bouncer-sheet1.png",
		"images/bouncer-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/bilet_-sheet0.png",
		"images/bilet_-sheet1.png",
		"images/bilet_-sheet2.png",
		"images/timesf.png",
		"images/migajacestrzalki_-sheet0.png",
		"images/migajacestrzalki_-sheet1.png",
		"images/poziombonusu_-sheet0.png",
		"images/paszczatygrys-sheet0.png",
		"images/paszczahippo-sheet0.png",
		"images/paszczalew-sheet0.png",
		"images/gwiazda_zapalona-sheet0.png",
		"images/gwiazda_zapalona-sheet1.png",
		"images/lampka_zapalona-sheet0.png",
		"images/detector-sheet0.png",
		"images/dziuranabilepodpaszcze-sheet0.png",
		"images/pausedicon-sheet0.png",
		"images/btnplay1-sheet0.png",
		"images/holdicon_2-sheet0.png",
		"images/scorefont.png",
		"images/htp_danger_-sheet0.png",
		"images/bannerswitchgames-sheet0.png",
		"images/bannerswitchgames-sheet1.png",
		"images/bannerswitchgames-sheet2.png",
		"images/avatarimg-sheet0.png",
		"images/globallabel-sheet0.png",
		"images/loadingarrows-sheet0.png",
		"images/friendslabel-sheet0.png",
		"images/loadinglabelt-sheet0.png",
		"images/pausediconpng-sheet0.png",
		"images/linelb-sheet0.png",
		"images/arabyads_240x-sheet0.png",
		"images/preloadergraphics_png2-sheet0.png",
		"images/preloadergraphics_png3-sheet0.png",
		"images/btnmoregames-sheet0.png",
		"media/bumper_02.m4a",
		"media/bumper_02.ogg",
		"media/bumper_03.m4a",
		"media/bumper_03.ogg",
		"media/bumper_04.m4a",
		"media/bumper_04.ogg",
		"media/pinball score_01.m4a",
		"media/pinball score_01.ogg",
		"media/pinball score_04.m4a",
		"media/pinball score_04.ogg",
		"media/pinball score_07.m4a",
		"media/pinball score_07.ogg",
		"media/tap sound 01.m4a",
		"media/tap sound 01.ogg",
		"media/tap sound 02 .m4a",
		"media/tap sound 02 .ogg",
		"media/tap sound 03.m4a",
		"media/tap sound 03.ogg",
		"media/tap sound 04.m4a",
		"media/tap sound 04.ogg",
		"media/bear roar 01.m4a",
		"media/bear roar 01.ogg",
		"media/bear roar 02.m4a",
		"media/bear roar 02.ogg",
		"media/bear roar 03.m4a",
		"media/bear roar 03.ogg",
		"media/scoring 03.m4a",
		"media/scoring 03.ogg",
		"media/scoring 01.m4a",
		"media/scoring 01.ogg",
		"media/scoring 02.m4a",
		"media/scoring 02.ogg",
		"media/pinball score_02.m4a",
		"media/pinball score_02.ogg",
		"media/zoo delete.m4a",
		"media/zoo delete.ogg",
		"media/tap sound 01b.m4a",
		"media/tap sound 01b.ogg",
		"media/zoo pinball music.m4a",
		"media/zoo pinball music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ga_init.js"
	]
}