{
	"version": 1494497177,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/btnbacktomain-sheet0.png",
		"images/btnbacktomain-sheet1.png",
		"images/btnsoundunmute-sheet0.png",
		"images/btnsoundunmute-sheet1.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundmute-sheet1.png",
		"images/btnplay-sheet0.png",
		"images/btnplay-sheet1.png",
		"images/btnselectbird-sheet0.png",
		"images/btnselectbird-sheet1.png",
		"images/btn_yes_green-sheet0.png",
		"images/btnpause-sheet0.png",
		"images/btnpause-sheet1.png",
		"images/btnmoregames-sheet0.png",
		"images/btnmoregames-sheet1.png",
		"images/logoblackmoon-sheet0.png",
		"images/pausecurtain.png",
		"images/bmlogo-sheet0.png",
		"images/coverasset-sheet0.png",
		"images/coverasset-sheet1.png",
		"images/doyouwanttoexit-sheet0.png",
		"images/gametitle1-sheet0.png",
		"images/howtoplay-sheet0.png",
		"images/highscore-sheet0.png",
		"images/howtoplay2-sheet0.png",
		"images/howtoplay2-sheet1.png",
		"images/howtoplay2-sheet2.png",
		"images/htp_aimhere-sheet0.png",
		"images/htp_aimhere-sheet1.png",
		"images/newbesthighscore-sheet0.png",
		"images/pausedcurtain-sheet0.png",
		"images/levelend-sheet0.png",
		"images/scorepanel-sheet0.png",
		"images/panelzgwiazdami-sheet0.png",
		"images/paneldoptakow-sheet0.png",
		"images/preloaderfont2.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/timesf.png",
		"images/flashscreen-sheet0.png",
		"images/taptocontinue-sheet0.png",
		"images/coverbackground-sheet0.png",
		"images/preloadergraphics_png2-sheet0.png",
		"images/girloncoverpng-sheet0.png",
		"images/gamebg-sheet0.png",
		"images/kitchenitems-sheet0.png",
		"images/kitchenitems-sheet1.png",
		"images/kitchenitems-sheet2.png",
		"images/table-sheet0.png",
		"images/itempoint-sheet0.png",
		"images/pasekdonapisow-sheet0.png",
		"images/kitchentxt-sheet0.png",
		"images/kitchentxt-sheet1.png",
		"images/kitchentxt-sheet2.png",
		"images/gardenitems-sheet0.png",
		"images/gardentxt-sheet0.png",
		"images/streetitems-sheet0.png",
		"images/streetitems-sheet1.png",
		"images/streettxt-sheet0.png",
		"images/streettxt-sheet1.png",
		"images/loadinglabel-sheet0.png",
		"images/staranim-sheet0.png",
		"images/missedtap_-sheet0.png",
		"images/gamecomplete_bg-sheet0.png",
		"images/coverillustration-sheet0.png",
		"images/gamecompelte_text-sheet0.png",
		"images/htp2-sheet0.png",
		"images/starico-sheet0.png",
		"images/gardenitems2old-sheet0.png",
		"images/collisionshape-sheet0.png",
		"images/gameprogress_-sheet0.png",
		"images/gametitle2-sheet0.png",
		"images/btnplay1-sheet0.png",
		"images/preloadergraphics_png3-sheet0.png",
		"media/net_04.m4a",
		"media/net_04.ogg",
		"media/star_02.m4a",
		"media/star_02.ogg",
		"media/eagle.m4a",
		"media/eagle.ogg",
		"media/pigeon eating.m4a",
		"media/pigeon eating.ogg",
		"media/button tap_03.m4a",
		"media/button tap_03.ogg",
		"media/bling_01.m4a",
		"media/bling_01.ogg",
		"media/bling_02.m4a",
		"media/bling_02.ogg",
		"media/hunter.m4a",
		"media/hunter.ogg",
		"media/spider.m4a",
		"media/spider.ogg",
		"media/wild cat_1.m4a",
		"media/wild cat_1.ogg",
		"media/wild cat_2.m4a",
		"media/wild cat_2.ogg",
		"media/wild cat_3.m4a",
		"media/wild cat_3.ogg",
		"media/click on the proper item_1.m4a",
		"media/click on the proper item_1.ogg",
		"media/click on the proper item_2.m4a",
		"media/click on the proper item_2.ogg",
		"media/click on the proper item_3.m4a",
		"media/click on the proper item_3.ogg",
		"media/click on the proper item_4.m4a",
		"media/click on the proper item_4.ogg",
		"media/click on the proper item_5.m4a",
		"media/click on the proper item_5.ogg",
		"media/click on the proper item_6.m4a",
		"media/click on the proper item_6.ogg",
		"media/click on the proper item_7.m4a",
		"media/click on the proper item_7.ogg",
		"media/level completed jingle_1.m4a",
		"media/level completed jingle_1.ogg",
		"media/where is tom music.m4a",
		"media/where is tom music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}