{
	"version": 1559209742,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/btnbacktomain-sheet0.png",
		"images/btnbacktomain-sheet1.png",
		"images/btnbacktomain-sheet2.png",
		"images/btnsoundunmute-sheet0.png",
		"images/btnsoundunmute-sheet1.png",
		"images/btnsoundunmute-sheet2.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundmute-sheet1.png",
		"images/btnsoundmute-sheet2.png",
		"images/btnplay-sheet0.png",
		"images/btnplay-sheet1.png",
		"images/btnplay-sheet2.png",
		"images/btn_levels_down_green-sheet0.png",
		"images/btn_levels_down_green-sheet1.png",
		"images/btn_levels_down_green-sheet2.png",
		"images/btnpause-sheet0.png",
		"images/btnpause-sheet1.png",
		"images/btnpause-sheet2.png",
		"images/btn_restart_down_green-sheet0.png",
		"images/btn_restart_down_green-sheet1.png",
		"images/btn_restart_down_green-sheet2.png",
		"images/btnyes-sheet0.png",
		"images/btnyes-sheet1.png",
		"images/btnmoregames-sheet0.png",
		"images/btnmoregames-sheet1.png",
		"images/btnmoregames-sheet2.png",
		"images/logoblackmoon-sheet0.png",
		"images/pausecurtain.png",
		"images/coverasset-sheet0.png",
		"images/covernumber-sheet0.png",
		"images/bg05-sheet0.png",
		"images/bg01_desert-sheet0.png",
		"images/howtoplay-sheet0.png",
		"images/howtoplay-sheet1.png",
		"images/howtoplay2-sheet0.png",
		"images/howtoplay2-sheet1.png",
		"images/howtoplay2-sheet2.png",
		"images/htp_aimhere-sheet0.png",
		"images/htp_aimhere-sheet1.png",
		"images/gametitle2-sheet0.png",
		"images/greatshot_-sheet0.png",
		"images/greatshot_-sheet1.png",
		"images/levelend-sheet0.png",
		"images/levelend-sheet1.png",
		"images/bg02_darkforest-sheet0.png",
		"images/doyouwanttoexit-sheet0.png",
		"images/threepoints-sheet0.png",
		"images/highscore-sheet0.png",
		"images/newbesthighscore-sheet0.png",
		"images/scorepanel-sheet0.png",
		"images/bmlogo-sheet0.png",
		"images/al_frame-sheet0.png",
		"images/al_frame-sheet1.png",
		"images/preloadergraphics_png2-sheet0.png",
		"images/bmlogo2-sheet0.png",
		"images/taptocontinue-sheet0.png",
		"images/pausedcurtain-sheet0.png",
		"images/dzyndzol-sheet0.png",
		"images/hudhealth-sheet0.png",
		"images/hudhealth-sheet1.png",
		"images/preloaderfont.png",
		"images/ballsmallicon-sheet0.png",
		"images/ballsmallicon-sheet1.png",
		"images/ballsmallicon-sheet2.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/airblower-sheet0.png",
		"images/airblower-sheet1.png",
		"images/ballanim-sheet0.png",
		"images/ballanim-sheet1.png",
		"images/basket-sheet0.png",
		"images/air_-sheet0.png",
		"images/air_-sheet1.png",
		"images/dym_particle_-sheet0.png",
		"images/dym_particle_-sheet1.png",
		"images/dym_particle_-sheet2.png",
		"images/glasstile-sheet0.png",
		"images/glasstile-sheet1.png",
		"images/gum_bumper-sheet0.png",
		"images/gum_bumper-sheet1.png",
		"images/kostka_glass_long-sheet0.png",
		"images/kostka_glass_medium-sheet0.png",
		"images/kostka_steelfixed-sheet0.png",
		"images/kostka_stone-sheet0.png",
		"images/kostka_stone_long-sheet0.png",
		"images/kostka_stone_medium-sheet0.png",
		"images/kostka_wood01_medium-sheet0.png",
		"images/obstacleparticle-sheet0.png",
		"images/obstacleparticle-sheet1.png",
		"images/enemy1-sheet0.png",
		"images/enemy1-sheet1.png",
		"images/enemy2-sheet0.png",
		"images/recthitbox-sheet0.png",
		"images/recttest-sheet0.png",
		"images/recttestanch-sheet0.png",
		"images/warp_in-sheet0.png",
		"images/warp_in-sheet1.png",
		"images/warp_out-sheet0.png",
		"images/warp_out-sheet1.png",
		"images/woodtile-sheet0.png",
		"images/woodtile-sheet1.png",
		"images/smugarogers-sheet0.png",
		"images/siatka_-sheet0.png",
		"images/siatka_-sheet1.png",
		"images/siatka_-sheet2.png",
		"images/timesf.png",
		"images/flashscreen-sheet0.png",
		"images/preloadersf.png",
		"images/pointempty-sheet0.png",
		"images/pointempty-sheet1.png",
		"images/preloaderfont2.png",
		"images/sprite2-sheet0.png",
		"images/hourglass-sheet0.png",
		"images/animacjasmiercikulka_-sheet0.png",
		"images/animacjasmiercikulka_-sheet1.png",
		"images/btnlevel-sheet0.png",
		"images/btnlevel-sheet1.png",
		"images/btnlevel-sheet2.png",
		"images/btnright-sheet0.png",
		"images/btnright-sheet1.png",
		"images/btnright-sheet2.png",
		"images/btnleft-sheet0.png",
		"images/btnleft-sheet1.png",
		"images/btnleft-sheet2.png",
		"images/lockedlevel-sheet0.png",
		"images/levelbtnnum.png",
		"images/blackcurtain-sheet0.png",
		"images/bg03_city-sheet0.png",
		"images/bg04_jungle-sheet0.png",
		"images/gameoverstar1-sheet0.png",
		"images/gameoverstar1-sheet1.png",
		"images/gameoverstaricon-sheet0.png",
		"images/parkietboiska-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/playerone_-sheet0.png",
		"images/playerone_-sheet1.png",
		"images/playertwo_-sheet0.png",
		"images/playertwo_-sheet1.png",
		"images/playertwoshadow_-sheet0.png",
		"images/playeroneshadow_-sheet0.png",
		"images/tlocovera_pustahala-sheet0.png",
		"images/szybszawidownia_-sheet0.png",
		"images/banda-sheet0.png",
		"images/paneldolevelu-sheet0.png",
		"images/efektdmuchania_-sheet0.png",
		"images/efektdmuchania_-sheet1.png",
		"images/skiplevel-sheet0.png",
		"images/skiplevel-sheet1.png",
		"images/skiplabel-sheet0.png",
		"images/usedskipicon-sheet0.png",
		"images/btnplay1-sheet0.png",
		"images/preloadergraphics_png3-sheet0.png",
		"images/adicon-sheet0.png",
		"media/ball bounce_02.m4a",
		"media/ball bounce_02.ogg",
		"media/net_04.m4a",
		"media/net_04.ogg",
		"media/ice tile crash.m4a",
		"media/ice tile crash.ogg",
		"media/armata.m4a",
		"media/armata.ogg",
		"media/teleport_03.m4a",
		"media/teleport_03.ogg",
		"media/fanloop.m4a",
		"media/fanloop.ogg",
		"media/scoring 02.m4a",
		"media/scoring 02.ogg",
		"media/scoring 02b.m4a",
		"media/scoring 02b.ogg",
		"media/glass1.m4a",
		"media/glass1.ogg",
		"media/glass2.m4a",
		"media/glass2.ogg",
		"media/glass3.m4a",
		"media/glass3.ogg",
		"media/wood break1.m4a",
		"media/wood break1.ogg",
		"media/c1.m4a",
		"media/c1.ogg",
		"media/c2.m4a",
		"media/c2.ogg",
		"media/crash bandicoot sounds - crate break1.m4a",
		"media/crash bandicoot sounds - crate break1.ogg",
		"media/c1a.m4a",
		"media/c1a.ogg",
		"media/c1b.m4a",
		"media/c1b.ogg",
		"media/bandi1.m4a",
		"media/bandi1.ogg",
		"media/bandi2.m4a",
		"media/bandi2.ogg",
		"media/bglass1.m4a",
		"media/bglass1.ogg",
		"media/bglass2.m4a",
		"media/bglass2.ogg",
		"media/bglass3.m4a",
		"media/bglass3.ogg",
		"media/bglass4.m4a",
		"media/bglass4.ogg",
		"media/super jump_01.m4a",
		"media/super jump_01.ogg",
		"media/create break.m4a",
		"media/create break.ogg",
		"media/fan_noise_01.m4a",
		"media/fan_noise_01.ogg",
		"media/fan_noise_loop_01_update.m4a",
		"media/fan_noise_loop_01_update.ogg",
		"media/glass break_01.m4a",
		"media/glass break_01.ogg",
		"media/glass break_02.m4a",
		"media/glass break_02.ogg",
		"media/glass break_03.m4a",
		"media/glass break_03.ogg",
		"media/glass break_04.m4a",
		"media/glass break_04.ogg",
		"media/glass hit_01.m4a",
		"media/glass hit_01.ogg",
		"media/glass hit_02.m4a",
		"media/glass hit_02.ogg",
		"media/wood break_03.m4a",
		"media/wood break_03.ogg",
		"media/wood break_1.m4a",
		"media/wood break_1.ogg",
		"media/wood break_1a.m4a",
		"media/wood break_1a.ogg",
		"media/wood break_1b.m4a",
		"media/wood break_1b.ogg",
		"media/wood break_2.m4a",
		"media/wood break_2.ogg",
		"media/basketballmaster tune.ogg",
		"media/basketballmaster tune.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ga_init.js"
	]
}