{
	"version": 1625050253,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/preloaderfont.png",
		"images/smallwhite.png",
		"images/largewhite.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundmute-sheet1.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/pausedlabel-sheet0.png",
		"images/pausecurtain-sheet0.png",
		"images/btnpause-sheet0.png",
		"images/btnpause-sheet1.png",
		"images/btnpause-sheet2.png",
		"images/util_centerobject_decoy-sheet0.png",
		"images/util_animation_decoy-sheet0.png",
		"images/util_buttons_decoy-sheet0.png",
		"images/cover_logo-sheet0.png",
		"images/flashscreen-sheet0.png",
		"images/btnpause2-sheet0.png",
		"images/btnpause2-sheet1.png",
		"images/btnpause2-sheet2.png",
		"images/btnpause3-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/cover_moregames-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/cover_title-sheet0.png",
		"images/cover_scorepanel-sheet0.png",
		"images/cover_highscore-sheet0.png",
		"images/cover_btnmoregames5-sheet0.png",
		"images/cover_btnmoregames5-sheet1.png",
		"images/cover_btnmoregames5-sheet2.png",
		"images/btnchoose_1-sheet0.png",
		"images/btnchoose_1-sheet1.png",
		"images/btnchoose_1-sheet2.png",
		"images/sprite4-sheet0.png",
		"images/player1-sheet0.png",
		"images/barrier_right-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/starmov-sheet0.png",
		"images/cloud_1-sheet0.png",
		"images/cloud_1-sheet1.png",
		"images/cloud_1-sheet2.png",
		"images/sprite11-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/explosion-sheet2.png",
		"images/smoke-sheet0.png",
		"images/smoke-sheet1.png",
		"images/sprite20-sheet0.png",
		"images/warning-sheet0.png",
		"images/warning-sheet1.png",
		"images/bgcloud_1-sheet0.png",
		"images/bgcloud_2-sheet0.png",
		"images/bgcloud_9-sheet0.png",
		"images/cloud_2-sheet0.png",
		"images/cloud_2-sheet1.png",
		"images/starstat-sheet0.png",
		"images/player2-sheet0.png",
		"images/player2-sheet1.png",
		"images/player2-sheet2.png",
		"images/player3-sheet0.png",
		"images/player3-sheet1.png",
		"images/player3-sheet2.png",
		"images/player4-sheet0.png",
		"images/player5-sheet0.png",
		"images/scorebestest-sheet0.png",
		"images/preloadergraphics_png2-sheet0.png",
		"images/preloaderfont2.png",
		"images/btnplay1-sheet0.png",
		"images/preloadergraphics_png3-sheet0.png",
		"images/curmoneyfont.png",
		"images/tut_2-sheet0.png",
		"images/tut_1-sheet0.png",
		"images/tut_1-sheet1.png",
		"images/tut_1-sheet2.png",
		"images/tut_3-sheet0.png",
		"images/banner-sheet0.png",
		"images/leaderboardbackground-sheet0.png",
		"images/leaderboardplayericon-sheet0.png",
		"images/leaderboardfont.png",
		"images/leaderboardplayerphoto_1-sheet0.png",
		"images/leaderboardplayerphoto_2-sheet0.png",
		"images/labelinvitefriend-sheet0.png",
		"images/labelfriends-sheet0.png",
		"images/leaderboardlines-sheet0.png",
		"images/bmchars-sheet0.png",
		"images/preloadergreenpercent.png",
		"media/music.m4a",
		"media/music.ogg",
		"media/button tap_03.m4a",
		"media/button tap_03.ogg",
		"media/catching ballon_01.m4a",
		"media/catching ballon_01.ogg",
		"media/catching ballon_04.m4a",
		"media/catching ballon_04.ogg",
		"media/plane crash_03.m4a",
		"media/plane crash_03.ogg",
		"media/star_02.m4a",
		"media/star_02.ogg",
		"media/catching ballon_03.m4a",
		"media/catching ballon_03.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ga_init.js"
	]
}