{
	"version": 1626019692,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/pumpkin-sheet0.png",
		"images/pumpkin-sheet1.png",
		"images/pumpkin-sheet2.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite4-sheet2.png",
		"images/btnbacktomain-sheet0.png",
		"images/btnbacktomain-sheet1.png",
		"images/btnbacktomain-sheet2.png",
		"images/btncontinue-sheet0.png",
		"images/btncontinue-sheet1.png",
		"images/btncontinue-sheet2.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundmute-sheet1.png",
		"images/btnpause-sheet0.png",
		"images/btnpause-sheet1.png",
		"images/btnpause-sheet2.png",
		"images/btnrestart-sheet0.png",
		"images/btnrestart-sheet1.png",
		"images/btnrestart-sheet2.png",
		"images/cover_moregames-sheet0.png",
		"images/cover_moregames-sheet1.png",
		"images/cover_moregames-sheet2.png",
		"images/coverbackground-sheet0.png",
		"images/covertitle-sheet0.png",
		"images/imgnewhighscore-sheet0.png",
		"images/lblbestscore-sheet0.png",
		"images/lblnewscore-sheet0.png",
		"images/lblpaused-sheet0.png",
		"images/logoblackmoon-sheet0.png",
		"images/pausecurtain.png",
		"images/imggameover-sheet0.png",
		"images/imghowtoplay-sheet0.png",
		"images/coverbackground2-sheet0.png",
		"images/curmoneyfont.png",
		"images/preloaderfont.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/publisherlogo-sheet0.png",
		"images/pinner-sheet0.png",
		"images/btnplay1-sheet0.png",
		"images/boundhelperbottomleft-sheet0.png",
		"images/pumpkinpart-sheet0.png",
		"images/pumpkinpart-sheet1.png",
		"images/pumpkinpart-sheet2.png",
		"images/banner-sheet0.png",
		"images/bmchars-sheet0.png",
		"images/preloadergreenpercent.png",
		"images/leaderboardbackground-sheet0.png",
		"images/labelfriends-sheet0.png",
		"images/leaderboardlines-sheet0.png",
		"images/leaderboardplayericon-sheet0.png",
		"images/leaderboardfont.png",
		"images/leaderboardplayerphoto_1-sheet0.png",
		"images/leaderboardplayerphoto_2-sheet0.png",
		"images/labelinvitefriend-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/button tap_03.m4a",
		"media/button tap_03.ogg",
		"media/pumkin smash_01.m4a",
		"media/pumkin smash_01.ogg",
		"media/pumkin smash_02.m4a",
		"media/pumkin smash_02.ogg",
		"media/pumkin smash_03.m4a",
		"media/pumkin smash_03.ogg",
		"media/pumkin smash_04.m4a",
		"media/pumkin smash_04.ogg",
		"media/pumkin smash_05.m4a",
		"media/pumkin smash_05.ogg",
		"media/bump_01.m4a",
		"media/bump_01.ogg",
		"media/music.m4a",
		"media/music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ga_init.js"
	]
}