{
	"version": 1519389473,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/btnbacktomain-sheet0.png",
		"images/btnbacktomain-sheet1.png",
		"images/btnbacktomain-sheet2.png",
		"images/btnsoundunmute-sheet0.png",
		"images/btnsoundunmute-sheet1.png",
		"images/btnsoundunmute-sheet2.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundmute-sheet1.png",
		"images/btnsoundmute-sheet2.png",
		"images/btnplay-sheet0.png",
		"images/btnplay-sheet1.png",
		"images/btnplay-sheet2.png",
		"images/btncontinue-sheet0.png",
		"images/btncontinue-sheet1.png",
		"images/btncontinue-sheet2.png",
		"images/btnplay2-sheet0.png",
		"images/btnplay2-sheet1.png",
		"images/btnplay2-sheet2.png",
		"images/btnplay1player-sheet0.png",
		"images/btnplay1player-sheet1.png",
		"images/btnplay1player-sheet2.png",
		"images/btnrestart-sheet0.png",
		"images/btnrestart-sheet1.png",
		"images/btnrestart-sheet2.png",
		"images/btnskip-sheet0.png",
		"images/btnskip-sheet1.png",
		"images/logoblackmoon-sheet0.png",
		"images/pausecurtain.png",
		"images/preloaderfont.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/gameplaybackground-sheet0.png",
		"images/coverbackground-sheet0.png",
		"images/scorepanel-sheet0.png",
		"images/timesf.png",
		"images/btnpause-sheet0.png",
		"images/btnpause-sheet1.png",
		"images/btnpause-sheet2.png",
		"images/pausedcurtain-sheet0.png",
		"images/gametitle-sheet0.png",
		"images/gameover-sheet0.png",
		"images/newbesthighscore-sheet0.png",
		"images/bmlogo-sheet0.png",
		"images/splashanim-sheet0.png",
		"images/splashanim-sheet1.png",
		"images/splashanim-sheet2.png",
		"images/howtoplay-sheet0.png",
		"images/btnmoregames-sheet0.png",
		"images/btnmoregames-sheet1.png",
		"images/btnmoregames-sheet2.png",
		"images/board-sheet0.png",
		"images/debugcoin-sheet0.png",
		"images/debugcoin-sheet1.png",
		"images/debugcoin-sheet2.png",
		"images/flashscreen-sheet0.png",
		"images/htp_touchdrag_-sheet0.png",
		"images/newhighscore_-sheet0.png",
		"images/coinicon-sheet0.png",
		"images/coinicon-sheet1.png",
		"images/tiledbackground.png",
		"images/kostkinacover-sheet0.png",
		"images/arrow-sheet0.png",
		"images/arrow-sheet1.png",
		"images/joint-sheet0.png",
		"images/joint-sheet1.png",
		"images/selectioncube-sheet0.png",
		"images/selectioncube-sheet1.png",
		"images/podswietlenietilesa-sheet0.png",
		"images/podswietlenietilesa-sheet1.png",
		"images/blysknacube-sheet0.png",
		"images/scorefont.png",
		"images/blockedtile-sheet0.png",
		"images/boardtile-sheet0.png",
		"images/buyanimbonusmedal-sheet0.png",
		"images/currentplayerselection-sheet0.png",
		"images/preloaderfont2.png",
		"images/preloadergraphics_png2-sheet0.png",
		"images/holdicon_2-sheet0.png",
		"images/outrostar-sheet0.png",
		"images/pausediconpng-sheet0.png",
		"images/uptocancelmove-sheet0.png",
		"images/preloadergraphics_png3-sheet0.png",
		"images/howtoplaylabel-sheet0.png",
		"media/cartoon tap_03.m4a",
		"media/cartoon tap_03.ogg",
		"media/fall die.m4a",
		"media/fall die.ogg",
		"media/blackmoonding.m4a",
		"media/blackmoonding.ogg",
		"media/sound of the vegetables dropping down_1.m4a",
		"media/sound of the vegetables dropping down_1.ogg",
		"media/sound of the vegetables dropping down_2.m4a",
		"media/sound of the vegetables dropping down_2.ogg",
		"media/sound of the vegetables dropping down_3.m4a",
		"media/sound of the vegetables dropping down_3.ogg",
		"media/sound of the vegetables dropping down_4.m4a",
		"media/sound of the vegetables dropping down_4.ogg",
		"media/sound of the vegetables dropping down_5.m4a",
		"media/sound of the vegetables dropping down_5.ogg",
		"media/moving_blocks_1.m4a",
		"media/moving_blocks_1.ogg",
		"media/moving_blocks_1_130.m4a",
		"media/moving_blocks_1_130.ogg",
		"media/moving_blocks_1_160.m4a",
		"media/moving_blocks_1_160.ogg",
		"media/moving_blocks_1_200.m4a",
		"media/moving_blocks_1_200.ogg",
		"media/moving_blocks_1_50.m4a",
		"media/moving_blocks_1_50.ogg",
		"media/moving_blocks_1_70.m4a",
		"media/moving_blocks_1_70.ogg",
		"media/moving_blocks_3.m4a",
		"media/moving_blocks_3.ogg",
		"media/sdropping down_1fast.m4a",
		"media/sdropping down_1fast.ogg",
		"media/sdropping down_2fast.m4a",
		"media/sdropping down_2fast.ogg",
		"media/sdropping down_3fast.m4a",
		"media/sdropping down_3fast.ogg",
		"media/sdropping down_4fast.m4a",
		"media/sdropping down_4fast.ogg",
		"media/sdropping down_5fast.m4a",
		"media/sdropping down_5fast.ogg",
		"media/click_1.m4a",
		"media/click_1.ogg",
		"media/click_2.m4a",
		"media/click_2.ogg",
		"media/click_3.m4a",
		"media/click_3.ogg",
		"media/falling_stars_2.m4a",
		"media/falling_stars_2.ogg",
		"media/enemy flies_2.m4a",
		"media/enemy flies_2.ogg",
		"media/enemy flies_2b.m4a",
		"media/enemy flies_2b.ogg",
		"media/enemy flies_2c.m4a",
		"media/enemy flies_2c.ogg",
		"media/enemy flies_2d.m4a",
		"media/enemy flies_2d.ogg",
		"media/tap_click on a button_10.m4a",
		"media/tap_click on a button_10.ogg",
		"media/tap_click on a button_11.m4a",
		"media/tap_click on a button_11.ogg",
		"media/tap_click on a button_12.m4a",
		"media/tap_click on a button_12.ogg",
		"media/tap_click on a button_7.m4a",
		"media/tap_click on a button_7.ogg",
		"media/tap_click on a button_8.l.m4a",
		"media/tap_click on a button_8.l.ogg",
		"media/tap_click on a button_9.m4a",
		"media/tap_click on a button_9.ogg",
		"media/moving_blocks_8.m4a",
		"media/moving_blocks_8.ogg",
		"media/tap_03.m4a",
		"media/tap_03.ogg",
		"media/falling_stars_1.m4a",
		"media/falling_stars_1.ogg",
		"media/complete_01.m4a",
		"media/complete_01.ogg",
		"media/connecting_blocks_3.m4a",
		"media/connecting_blocks_3.ogg",
		"media/level failed_3.m4a",
		"media/level failed_3.ogg",
		"media/riddlecubez_music.m4a",
		"media/riddlecubez_music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ga_init.js"
	]
}